import { describe, it, expect, vi } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { DataClient } from '@/core/data/dataClient'
import type { Transport } from '@/core/data/transport'
import type { Manifest } from '@/core/data/types'

const manifest: Manifest = {
  version: 'test',
  datasets: {
    qpc: { pathTemplate: 'data/qpc/pages/{page}.json', count: 604 },
    'tr-en': { pathTemplate: 'data/tr/en/{surah}.json', count: 114 },
  },
  indexes: { surahNames: { path: 'data/surah-names.json' } },
}

/** Mock transport returning canned JSON, recording calls. */
function mockTransport(files: Record<string, unknown>) {
  const calls: string[] = []
  const transport: Transport = {
    fetchJson: vi.fn(async (path: string) => {
      calls.push(path)
      if (!(path in files)) throw new Error(`404 ${path}`)
      return files[path] as never
    }),
  }
  return { transport, calls }
}

describe('DataClient (mock transport)', () => {
  it('loads manifest on init and serves typed pages', async () => {
    const { transport } = mockTransport({
      'data/manifest.json': manifest,
      'data/qpc/pages/1.json': { page: 1, layout: [], words: [] },
    })
    const client = new DataClient(transport)
    await client.init()
    expect(client.pageCount('qpc')).toBe(604)
    const page = await client.getPage('qpc', 1)
    expect(page.page).toBe(1)
  })

  it('throws when used before init', async () => {
    const { transport } = mockTransport({})
    const client = new DataClient(transport)
    expect(() => client.pageCount('qpc')).toThrow(/init/)
  })

  it('prefetch clamps out-of-range pages (no fetch)', async () => {
    const { transport, calls } = mockTransport({ 'data/manifest.json': manifest })
    const client = new DataClient(transport)
    await client.init()
    calls.length = 0
    client.prefetchPage('qpc', 0)
    client.prefetchPage('qpc', 605)
    expect(calls).toEqual([])
    client.prefetchPage('qpc', 5)
    expect(calls).toEqual(['data/qpc/pages/5.json'])
  })
})

// Integration: run the client against the REAL generated chunks when present
// (generated by `npm run build`/prebuild; skipped if not yet built).
// vitest runs with cwd = app/, so public/ holds the generated fixtures.
const PUBLIC = resolve(process.cwd(), 'public')
const hasData = existsSync(resolve(PUBLIC, 'data/manifest.json'))

describe.skipIf(!hasData)('DataClient (real generated fixtures)', () => {
  const fsTransport: Transport = {
    fetchJson: async (path: string) =>
      JSON.parse(readFileSync(resolve(PUBLIC, path), 'utf8')) as never,
  }

  it('serves a real QPC page 1 with layout + words', async () => {
    const client = new DataClient(fsTransport)
    await client.init()
    const page = await client.getPage('qpc', 1)
    expect(page.page).toBe(1)
    expect(page.layout.length).toBeGreaterThan(0)
    expect(page.words.length).toBeGreaterThan(0)
    expect(page.words[0].text.length).toBeGreaterThan(0)
    expect(page.words[0].location).toMatch(/^\d+:\d+:\d+$/)
  })

  it('serves real surah-1 English translations keyed by location', async () => {
    const client = new DataClient(fsTransport)
    await client.init()
    const tr = await client.getTranslations('en', 1)
    expect(tr['1:1:1']).toBeTruthy()
  })
})
