import { describe, it, expect, vi } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { DataClient } from '@/core/data/dataClient'
import type { Transport } from '@/core/data/transport'
import type { Manifest } from '@/core/data/types'

const manifest: Manifest = {
  version: 'test',
  datasets: {
    qpc: { pathTemplate: 'data/qpc/pages/{page}.json', count: 604, hash: 'qpchash' },
    'tr-en': { pathTemplate: 'data/tr/en/{surah}.json', count: 114, hash: 'trenhash' },
    morphology: { pathTemplate: 'data/morphology/{surah}.json', count: 114, hash: 'morphhash' },
    'quran-text': { pathTemplate: 'data/quran-text/{surah}.json', count: 114, hash: 'qtexthash' },
  },
  indexes: {
    surahNames: { path: 'data/surah-names.json', hash: 'namehash' },
    navQpc: { path: 'data/nav/qpc.json', hash: 'navqpchash' },
    navIndopak: { path: 'data/nav/indopak.json', hash: 'navindohash' },
  },
}

/** Mock transport returning canned JSON, recording calls. */
function mockTransport(files: Record<string, unknown>) {
  const calls: string[] = []
  const transport: Transport = {
    fetchJson: vi.fn(async (path: string) => {
      calls.push(path)
      if (!(path in files)) throw new Error(`404 ${path}`)
      return files[path] as never
    }),
  }
  return { transport, calls }
}

describe('DataClient (mock transport)', () => {
  it('loads manifest on init and serves typed pages', async () => {
    const { transport } = mockTransport({
      'data/manifest.json': manifest,
      'data/qpc/pages/1.json?v=qpchash': { page: 1, layout: [], words: [] },
    })
    const client = new DataClient(transport)
    await client.init()
    expect(client.pageCount('qpc')).toBe(604)
    const page = await client.getPage('qpc', 1)
    expect(page.page).toBe(1)
  })

  it('throws when used before init', async () => {
    const { transport } = mockTransport({})
    const client = new DataClient(transport)
    expect(() => client.pageCount('qpc')).toThrow(/init/)
  })

  it('getMorphology builds the per-surah path', async () => {
    const { transport, calls } = mockTransport({
      'data/manifest.json': manifest,
      'data/morphology/2.json?v=morphhash': { '2:255:1': '<i>the</i>' },
    })
    const client = new DataClient(transport)
    await client.init()
    calls.length = 0
    const morph = await client.getMorphology(2)
    expect(calls).toEqual(['data/morphology/2.json?v=morphhash'])
    expect(morph['2:255:1']).toContain('the')
  })

  it('getVerseText builds the per-surah path and serves plain Arabic', async () => {
    const { transport, calls } = mockTransport({
      'data/manifest.json': manifest,
      'data/quran-text/1.json?v=qtexthash': { '1:1': { text: 'بِسْمِ ٱللَّهِ' } },
    })
    const client = new DataClient(transport)
    await client.init()
    calls.length = 0
    const text = await client.getVerseText(1)
    expect(calls).toEqual(['data/quran-text/1.json?v=qtexthash'])
    expect(text['1:1'].text).toBe('بِسْمِ ٱللَّهِ')
  })

  it('getNavIndex picks the per-layout index path', async () => {
    const { transport, calls } = mockTransport({
      'data/manifest.json': manifest,
      'data/nav/qpc.json?v=navqpchash': { ayahToPage: {}, surahToPage: {}, juzToPage: {} },
      'data/nav/indopak.json?v=navindohash': { ayahToPage: {}, surahToPage: {}, juzToPage: {} },
    })
    const client = new DataClient(transport)
    await client.init()
    calls.length = 0
    await client.getNavIndex('qpc')
    await client.getNavIndex('indopak')
    expect(calls).toEqual(['data/nav/qpc.json?v=navqpchash', 'data/nav/indopak.json?v=navindohash'])
  })

  it('prefetch clamps out-of-range pages (no fetch)', async () => {
    const { transport, calls } = mockTransport({ 'data/manifest.json': manifest })
    const client = new DataClient(transport)
    await client.init()
    calls.length = 0
    client.prefetchPage('qpc', 0)
    client.prefetchPage('qpc', 605)
    expect(calls).toEqual([])
    client.prefetchPage('qpc', 5)
    expect(calls).toEqual(['data/qpc/pages/5.json?v=qpchash'])
  })
})

// Integration: run the client against the REAL generated chunks when present
// (generated by `npm run build`/prebuild; skipped if not yet built).
// vitest runs with cwd = app/, so public/ holds the generated fixtures.
const PUBLIC = resolve(process.cwd(), 'public')
const hasData = existsSync(resolve(PUBLIC, 'data/manifest.json'))

describe.skipIf(!hasData)('DataClient (real generated fixtures)', () => {
  const fsTransport: Transport = {
    // Real paths now carry a `?v=<hash>` cache-buster; a filesystem read (unlike
    // an HTTP request) needs it stripped to resolve the actual file on disk.
    fetchJson: async (path: string) =>
      JSON.parse(readFileSync(resolve(PUBLIC, path.split('?')[0]), 'utf8')) as never,
  }

  it('serves a real QPC page 1 with layout + words', async () => {
    const client = new DataClient(fsTransport)
    await client.init()
    const page = await client.getPage('qpc', 1)
    expect(page.page).toBe(1)
    expect(page.layout.length).toBeGreaterThan(0)
    expect(page.words.length).toBeGreaterThan(0)
    expect(page.words[0].text.length).toBeGreaterThan(0)
    expect(page.words[0].location).toMatch(/^\d+:\d+:\d+$/)
  })

  it('serves real surah-1 English translations keyed by location', async () => {
    const client = new DataClient(fsTransport)
    await client.init()
    const tr = await client.getTranslations('en', 1)
    expect(tr['1:1:1']).toBeTruthy()
  })

  it('resolves quick-jump targets to pages via the nav index', async () => {
    const client = new DataClient(fsTransport)
    await client.init()
    const nav = await client.getNavIndex('qpc')
    expect(nav.ayahToPage['2:255']).toBe(42) // Ayat al-Kursi
    expect(nav.surahToPage['36']).toBe(440) // Ya-Sin
    expect(nav.juzToPage['1']).toBe(1)
    expect(Object.keys(nav.juzToPage)).toHaveLength(30)
    // Indopak has its own paging (610 pages).
    const navIndo = await client.getNavIndex('indopak')
    expect(navIndo.ayahToPage['1:1']).toBe(1)
  })

  it('serves real per-surah morphology keyed by word location', async () => {
    const client = new DataClient(fsTransport)
    await client.init()
    const morph = await client.getMorphology(1)
    expect(morph['1:1:1']).toContain('س م و') // bismillah root, unwrapped from .data
    expect(Object.keys(morph).length).toBeGreaterThan(0)
  })

  it('serves real plain Arabic verse text, distinct from the QPC glyph font', async () => {
    const client = new DataClient(fsTransport)
    await client.init()
    const text = await client.getVerseText(1)
    expect(text['1:1'].text.length).toBeGreaterThan(0)
    // Not a presentation-form ligature (how the QPC glyph font hijacks Unicode
    // as glyph indices) — real text renders correctly without that font.
    for (const ch of text['1:1'].text) {
      const cp = ch.codePointAt(0)!
      expect(cp >= 0xfb50 && cp <= 0xfdff).toBe(false)
      expect(cp >= 0xfe70 && cp <= 0xfeff).toBe(false)
    }
    const page = await client.getPage('qpc', 1)
    const glyph = page.words.find((w) => w.location === '1:1:1')!.text
    expect(text['1:1'].text).not.toContain(glyph) // real Arabic ≠ font glyph text
  })
})
